Added option for user to choose the infra and node network interface …
noironetworks/openshift-bm pull request #3
Opened 2021-10-22 06:03 UTC by satishoc

2021-10-26 15:52 UTC, snaiksat commented on update_ign.py
> +        print("\n   Invalid Option, Please Try Again")
Could you please provide information about these options as a part of the comments section we have at the top of this script? We intend that to be the documentation on how to run this script and what options it supports.

2021-10-28 10:32 UTC, satishoc commented on update_ign.py
> +        print("\n   Invalid Option, Please Try Again")
Added

2021-10-28 14:15 UTC, abhis2112 commented on update_ign.py
> +    def create_interface_with_bond(self, interface_name, bond_name, mtu):
create_slave_interface

2021-10-28 14:15 UTC, abhis2112 commented on update_ign.py
> +            opflex_conn = ("""VLAN=yes
this code is repeated. Please modularize it

2021-10-28 14:15 UTC, abhis2112 commented on update_ign.py
> +            config_data['route_opflex_conn'] = {'base64': route_opflex_conn_b64, 'path': '/etc/sysconfig/network-scripts/route-opflex-conn'}
till here. Make a separate function if this code will be called again and again

2021-10-28 14:15 UTC, abhis2112 commented on update_ign.py
> +            for k, v in config_data.items():
make it more verbose. Like - interface, interface_config --> interface_config[path]

2021-11-01 06:37 UTC, satishoc commented on update_ign.py
> +            for k, v in config_data.items():
done

2021-11-01 06:37 UTC, satishoc commented on update_ign.py
> +    def create_interface_with_bond(self, interface_name, bond_name, mtu):
renamed

2021-11-01 07:27 UTC, satishoc commented on update_ign.py
> +            config_data['route_opflex_conn'] = {'base64': route_opflex_conn_b64, 'path': '/etc/sysconfig/network-scripts/route-opflex-conn'}
done

2021-11-10 01:40 UTC, snaiksat requested changes

2021-11-10 01:40 UTC, snaiksat commented on update_ign.py
> +#               currently we support option one only(please update interface name in config.yaml file)
> currently we support option one only

This comment is fine in the commit message but does not make sense here.  

> (please update interface name in config.yaml file)

This should be removed from the parentheses and clearly stated what changes need to be made in each case. So say something to the effect of:

    Please update the config.yaml as follows:

2021-11-10 01:40 UTC, snaiksat commented on update_ign.py
> +#           Please update the config.yaml file before running this script
Please remove this comment

2021-11-10 01:40 UTC, snaiksat commented on update_ign.py
> +#           Trigger the command after changing config.yaml file according to requirement:   python3 update_ign.py
Please revert this back to how it was earlier

2021-11-10 01:40 UTC, snaiksat commented on update_ign.py
> +#               we will have following option to choose from
How does this sentence tie into the existing text comments above it??

2021-11-23 18:16 UTC, snaiksat commented
Thanks @satishoc for updating the comment. @abhis2112  when you get a chance please check if the generated output provided by @satishoc for all the cases matches the expectations.

2021-11-24 06:52 UTC, abhis2112 approved these changes

2021-11-24 06:52 UTC, abhis2112 commented
lgtm

2022-06-04 08:46 UTC, snaiksat approved these changes

2022-06-04 08:46 UTC, merged